name: appsfactory_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dartz: ^0.10.1
  http: ^0.13.4
  json_annotation: ^4.5.0
  collection: ^1.16.0
  hive_flutter: ^1.1.0
  path: ^1.8.1
  get_it: ^7.2.0
  infinite_scroll_pagination: ^3.2.0
  path_provider: ^2.0.11
  another_flushbar: ^1.10.29

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  dart_code_metrics: ^4.16.0
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0
  mockito: ^5.2.0
  dependency_validator: ^3.2.0

flutter:
  uses-material-design: true
  generate: true